// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVok7B-dLa8NGr8Cqj4KOe225XBWrWmZU',
    appId: '1:412752509055:web:97329ab6aabdd43b7be74a',
    messagingSenderId: '412752509055',
    projectId: 'my-hotel-application',
    authDomain: 'my-hotel-application.firebaseapp.com',
    storageBucket: 'my-hotel-application.appspot.com',
    measurementId: 'G-9XZSGBDZLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGyGIOSfWHJdvFqi7-GlwaFn6imkPSmKk',
    appId: '1:412752509055:android:ea2317eb6424646b7be74a',
    messagingSenderId: '412752509055',
    projectId: 'my-hotel-application',
    storageBucket: 'my-hotel-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9llV6_1qO1x5SPId7f7WaZYlZ3gNRRL4',
    appId: '1:412752509055:ios:0acd7a961d53b24b7be74a',
    messagingSenderId: '412752509055',
    projectId: 'my-hotel-application',
    storageBucket: 'my-hotel-application.appspot.com',
    iosBundleId: 'com.example.myHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9llV6_1qO1x5SPId7f7WaZYlZ3gNRRL4',
    appId: '1:412752509055:ios:0acd7a961d53b24b7be74a',
    messagingSenderId: '412752509055',
    projectId: 'my-hotel-application',
    storageBucket: 'my-hotel-application.appspot.com',
    iosBundleId: 'com.example.myHotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVok7B-dLa8NGr8Cqj4KOe225XBWrWmZU',
    appId: '1:412752509055:web:86fa5af3c3052ede7be74a',
    messagingSenderId: '412752509055',
    projectId: 'my-hotel-application',
    authDomain: 'my-hotel-application.firebaseapp.com',
    storageBucket: 'my-hotel-application.appspot.com',
    measurementId: 'G-Q1VP7JQWJC',
  );

}